steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "northamerica-south1-docker.pkg.dev/tienda-microservices-459915/image-registry/client-gateway",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "northamerica-south1-docker.pkg.dev/tienda-microservices-459915/image-registry/client-gateway",
      ]
options:   
    logging: CLOUD_LOGGING_ONLY
    default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET